"use client"

import Link from "next/link"
import useSWR from "swr"
import { Activity, ArrowUpRight, CalendarCheck, Gauge, MessageSquareText, PhoneCall, Sparkles, Zap } from "lucide-react"
import { Button } from "@/components/ui/button"

const fetcher = (url: string) => fetch(url).then((r) => r.json())

type Call = { id: number; personaName: string | null; language: string; status: string; startedAt: string; durationSeconds: number | null; overallScore: number | null; avgLatencyMs: number | null }
type Stats = { totalCalls: number; completedCalls: number; totalDuration: number; avgScore: number; avgLatency: number; totalTurns: number; totalBookings: number; recentCalls: Call[]; sentiments: { sentiment: string; count: number }[] }

function Metric({ label, value, detail, icon: Icon }: { label: string; value: string | number; detail: string; icon: typeof PhoneCall }) {
  return <article className="rounded-xl border bg-card p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 font-mono text-3xl font-semibold tracking-tight">{value}</p></div><span className="rounded-lg bg-primary/10 p-2 text-primary"><Icon className="size-5" /></span></div><p className="mt-4 text-xs text-muted-foreground">{detail}</p></article>
}

export function DashboardClient() {
  const { data, isLoading } = useSWR<Stats>("/api/stats", fetcher, { refreshInterval: 10000 })
  const stats = data ?? { totalCalls: 0, completedCalls: 0, totalDuration: 0, avgScore: 0, avgLatency: 0, totalTurns: 0, totalBookings: 0, recentCalls: [], sentiments: [] }
  const minutes = Math.round(stats.totalDuration / 60)
  return <div className="min-h-svh p-5 md:p-8">
    <header className="flex flex-col justify-between gap-5 border-b pb-6 md:flex-row md:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-medium uppercase tracking-[0.18em] text-primary"><Activity className="size-4" />Voice operations center</div><h1 className="text-balance text-3xl font-semibold tracking-tight md:text-4xl">Your agents, calls and outcomes.<br /><span className="text-muted-foreground">One live operating system.</span></h1></div><Button nativeButton={false} render={<Link href="/call" />}><PhoneCall data-icon="inline-start" />Start live call</Button></header>
    <section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total calls" value={isLoading ? "—" : stats.totalCalls} detail={`${stats.completedCalls} completed`} icon={PhoneCall} /><Metric label="Average quality" value={`${stats.avgScore || 0}%`} detail="AI scored after every call" icon={Sparkles} /><Metric label="Voice latency" value={stats.avgLatency ? `${(stats.avgLatency / 1000).toFixed(1)}s` : "—"} detail="Speech end to first audio" icon={Zap} /><Metric label="Appointments" value={stats.totalBookings} detail={`${minutes} total call minutes`} icon={CalendarCheck} /></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_1fr]">
      <section className="rounded-xl border bg-card"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">Recent conversations</h2><p className="text-sm text-muted-foreground">Transcripts, quality and latency in one place</p></div><Button nativeButton={false} variant="ghost" size="sm" render={<Link href="/calls" />}>View all<ArrowUpRight data-icon="inline-end" /></Button></div><div className="divide-y">{stats.recentCalls.length ? stats.recentCalls.map((call) => <Link href={`/calls/${call.id}`} key={call.id} className="flex items-center justify-between gap-4 p-4 transition-colors hover:bg-accent"><div className="min-w-0"><p className="truncate text-sm font-medium">{call.personaName || "Voice agent"}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(call.startedAt).toLocaleString("en-IN")} · {call.language === "telugu" ? "Telugu" : "Hinglish"}</p></div><div className="flex shrink-0 items-center gap-4"><span className="hidden font-mono text-xs text-muted-foreground sm:inline">{call.avgLatencyMs ? `${(call.avgLatencyMs / 1000).toFixed(1)}s` : "—"}</span><span className="rounded-md bg-primary/10 px-2 py-1 font-mono text-xs text-primary">{call.overallScore ?? "—"}</span></div></Link>) : <div className="flex flex-col items-center gap-3 p-12 text-center"><MessageSquareText className="size-8 text-muted-foreground" /><div><p className="text-sm font-medium">No calls yet</p><p className="text-sm text-muted-foreground">Start a live call to create your first transcript.</p></div></div>}</div></section>
      <aside className="flex flex-col gap-4"><section className="rounded-xl border bg-card p-5"><div className="flex items-center gap-3"><Gauge className="size-5 text-primary" /><div><h2 className="font-semibold">Realtime pipeline</h2><p className="text-xs text-muted-foreground">Production services status</p></div></div><div className="mt-5 flex flex-col gap-3">{[["Ears", "Groq Whisper", "Telugu + code-switch"],["Brain", "Llama 3.3 70B", "Streaming + tools"],["Voice", "Sarvam Bulbul v2", "Natural Indian speech"],["Memory", "Neon Postgres", "Persistent analytics"]].map(([a,b,c]) => <div key={a} className="flex items-center justify-between rounded-lg bg-secondary p-3"><div><p className="text-xs text-muted-foreground">{a}</p><p className="text-sm font-medium">{b}</p></div><div className="text-right"><span className="text-xs text-primary">Operational</span><p className="text-[11px] text-muted-foreground">{c}</p></div></div>)}</div></section><section className="rounded-xl border border-primary/30 bg-primary/5 p-5"><p className="text-xs font-medium uppercase tracking-wider text-primary">Free-tier architecture</p><h3 className="mt-2 text-lg font-semibold">Built for realism before telephony</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Browser audio avoids telecom cost while preserving barge-in, adaptive voice activity detection, streamed reasoning and sentence-level speech synthesis.</p></section></aside>
    </div>
  </div>
}
