"use client"

import Link from "next/link"
import useSWR from "swr"
import { ArrowRight, Clock, FileText, PhoneCall } from "lucide-react"
import { Button } from "@/components/ui/button"

const fetcher = (url: string) => fetch(url).then((r) => r.json())
type Call = { id:number; personaName:string|null; language:string; status:string; startedAt:string; durationSeconds:number|null; overallScore:number|null; summary:string|null; sentiment:string|null; avgLatencyMs:number|null; turnCount:number }

export default function CallsPage() {
 const { data = [], isLoading } = useSWR<Call[]>("/api/calls", fetcher)
 return <div className="min-h-svh p-5 md:p-8"><header className="flex flex-col justify-between gap-4 border-b pb-6 sm:flex-row sm:items-end"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-primary">Conversation intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Call history</h1><p className="mt-2 text-sm text-muted-foreground">Every transcript, summary, score and latency trace.</p></div><Button nativeButton={false} render={<Link href="/call" />}><PhoneCall data-icon="inline-start" />New call</Button></header><section className="mt-6 overflow-hidden rounded-xl border bg-card"><div className="hidden grid-cols-[1.3fr_.7fr_.7fr_.7fr_40px] gap-4 border-b px-5 py-3 text-xs uppercase tracking-wider text-muted-foreground md:grid"><span>Conversation</span><span>Duration</span><span>Latency</span><span>Score</span><span /></div>{isLoading ? <p className="p-10 text-center text-sm text-muted-foreground">Loading calls...</p> : data.length ? data.map((call) => <Link key={call.id} href={`/calls/${call.id}`} className="grid gap-3 border-b p-5 transition-colors last:border-b-0 hover:bg-accent md:grid-cols-[1.3fr_.7fr_.7fr_.7fr_40px] md:items-center"><div><p className="font-medium">{call.personaName || "Voice agent"}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(call.startedAt).toLocaleString("en-IN")} · {call.language === "telugu" ? "Telugu" : "Hinglish"} · {call.turnCount} turns</p><p className="mt-2 line-clamp-1 text-sm text-muted-foreground">{call.summary || (call.status === "active" ? "Call in progress" : "Analysis pending")}</p></div><p className="flex items-center gap-2 font-mono text-sm"><Clock className="size-4 text-muted-foreground" />{call.durationSeconds ? `${Math.floor(call.durationSeconds/60)}m ${call.durationSeconds%60}s` : "—"}</p><p className="font-mono text-sm">{call.avgLatencyMs ? `${(call.avgLatencyMs/1000).toFixed(2)}s` : "—"}</p><div><span className="rounded-md bg-primary/10 px-2 py-1 font-mono text-sm text-primary">{call.overallScore ?? "—"}</span></div><ArrowRight className="size-4 text-muted-foreground" /></Link>) : <div className="flex flex-col items-center gap-3 p-16 text-center"><FileText className="size-9 text-muted-foreground" /><p className="font-medium">No conversations recorded</p><p className="text-sm text-muted-foreground">Completed calls will appear here automatically.</p></div>}</section></div>
}
